# Praktikum 1

In [1]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.25524583607840745
Epoch 1000, Loss: 0.2500107032468195
Epoch 2000, Loss: 0.2499630715529133
Epoch 3000, Loss: 0.24988843594263688
Epoch 4000, Loss: 0.24966589242882556
Epoch 5000, Loss: 0.2487766715834715
Epoch 6000, Loss: 0.24312975489928426
Epoch 7000, Loss: 0.21276406806177237
Epoch 8000, Loss: 0.15522311355085394
Epoch 9000, Loss: 0.05175774717755194
Prediksi:
[[0.14673223]
 [0.84648375]
 [0.83319328]
 [0.12951705]]


Tugas 1:
- Ubah jumlah neuron hidden layer menjadi 3.
- Bandingkan hasil loss dengan konfigurasi awal.
- Tambahkan fungsi aktivasi ReLU dan bandingkan hasil.



In [2]:
import numpy as np

# Agar hasil konsisten (reproducible)
np.random.seed(42)

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# --- PERUBAHAN TUGAS 1 ---
# Mengubah hidden_size dari 2 menjadi 3
input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi (Sigmoid)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

print("--- TRAINING DENGAN 3 HIDDEN NEURONS (SIGMOID) ---")
# Training
for epoch in range(10001):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 2000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss:.6f}")

# Output akhir
print("\nPrediksi Akhir:")
print(a2)

--- TRAINING DENGAN 3 HIDDEN NEURONS (SIGMOID) ---
Epoch 0, Loss: 0.318245
Epoch 2000, Loss: 0.141854
Epoch 4000, Loss: 0.020112
Epoch 6000, Loss: 0.006270
Epoch 8000, Loss: 0.003421
Epoch 10000, Loss: 0.002297

Prediksi Akhir:
[[0.02515318]
 [0.95264015]
 [0.95122762]
 [0.06271949]]


In [3]:
import numpy as np

np.random.seed(42)

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3 # Tetap pakai 3 agar adil perbandingannya
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# --- FUNGSI AKTIVASI BARU (RELU) ---
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    # Turunan ReLU adalah 1 jika x > 0, selain itu 0
    return (x > 0).astype(float)

# Sigmoid tetap dipakai untuk Output Layer
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

print("--- TRAINING DENGAN RELU (HIDDEN) & SIGMOID (OUTPUT) ---")

# Training
for epoch in range(10001):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)      # <--- GANTI JADI RELU

    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)   # Output tetap Sigmoid

    # Hitung error
    error = y - a2

    # Backpropagation

    # Layer 2 (Output) - Tetap pakai turunan Sigmoid
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    # Layer 1 (Hidden) - GANTI JADI TURUNAN RELU
    # Kita gunakan z1 untuk cek turunan ReLU (apakah input > 0)
    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)

    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 2000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss:.6f}")

print("\nPrediksi Akhir (ReLU):")
print(a2)

--- TRAINING DENGAN RELU (HIDDEN) & SIGMOID (OUTPUT) ---
Epoch 0, Loss: 0.327478
Epoch 2000, Loss: 0.003283
Epoch 4000, Loss: 0.001147
Epoch 6000, Loss: 0.000666
Epoch 8000, Loss: 0.000462
Epoch 10000, Loss: 0.000351

Prediksi Akhir (ReLU):
[[0.02969834]
 [0.98607299]
 [0.98607278]
 [0.0116511 ]]
